language: android

android:
  components:
    - tools
    - build-tools-27.0.0
    - build-tools-26.0.2
    - android-27
    - android-19
    - extra-android-m2repository

script:
  ./gradlew checkstyle build
